#!/bin/bash
# Background Compaction - Stop hook
# 토큰 한계 도달 시 자동 압축 알림
# Based on oh-my-opencode's background-compaction

INPUT=$(cat)
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
NOTEPADS_DIR="$PROJECT_DIR/.claude/notepads"
LOG_FILE="$NOTEPADS_DIR/context-monitor.log"

# Check if context limit is approaching
if [ -f "$LOG_FILE" ]; then
    LAST_LINE=$(tail -1 "$LOG_FILE" 2>/dev/null)

    # Extract percentage if available
    if echo "$LAST_LINE" | grep -q "Context:"; then
        PERCENTAGE=$(echo "$LAST_LINE" | grep -oE '[0-9]+%' | head -1 | tr -d '%')

        if [ -n "$PERCENTAGE" ] && [ "$PERCENTAGE" -ge 90 ]; then
            echo ""
            echo "[background-compaction] ⚠️ Context window at ${PERCENTAGE}%"
            echo "[background-compaction] Consider:"
            echo "  1. Save important context to .claude/notes/"
            echo "  2. Use /compact to summarize conversation"
            echo "  3. Start new session for fresh context"
            echo ""

            # Auto-save session summary
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
            SUMMARY_FILE="$PROJECT_DIR/.claude/notes/session_${TIMESTAMP}.md"

            mkdir -p "$PROJECT_DIR/.claude/notes"

            cat > "$SUMMARY_FILE" << EOF
# Session Summary - $TIMESTAMP

## Context Limit Warning
Context usage reached ${PERCENTAGE}%.

## Active Modes
$(cat "$NOTEPADS_DIR/active-modes.txt" 2>/dev/null || echo "None")

## Recommended Actions
- Review completed tasks
- Save important decisions
- Continue in new session if needed

---
*Auto-generated by background-compaction hook*
EOF

            echo "[background-compaction] Session summary saved to: $SUMMARY_FILE"
        fi
    fi
fi

exit 0
