#!/bin/bash

# Unity System Structure Creator
# 폴더 명명 규칙: XX_FolderName (CLAUDE.md 준수)
# 사용법: ./create-structure.sh <시스템이름> [프로젝트경로]

set -e

SYSTEM_NAME=$1
PROJECT_PATH=${2:-"Assets"}
SCRIPTS_PATH="$PROJECT_PATH/01_Scripts"
SYSTEMS_PATH="$SCRIPTS_PATH/03_Systems"

# 색상 정의
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 사용법 출력
if [ -z "$SYSTEM_NAME" ]; then
    echo "사용법: ./create-structure.sh <시스템이름> [프로젝트경로]"
    echo "예시: ./create-structure.sh Inventory"
    echo "예시: ./create-structure.sh Inventory Assets"
    exit 1
fi

# 다음 폴더 번호 계산
get_next_number() {
    local path=$1
    local max=0

    if [ -d "$path" ]; then
        for dir in "$path"/*/; do
            if [ -d "$dir" ]; then
                num=$(basename "$dir" | grep -oE '^[0-9]+' || echo "0")
                if [ "$num" -gt "$max" ] 2>/dev/null; then
                    max=$num
                fi
            fi
        done
    fi

    printf "%02d" $((max + 1))
}

# 시스템 폴더 번호 계산
SYSTEM_NUM=$(get_next_number "$SYSTEMS_PATH")
SYSTEM_FOLDER="${SYSTEM_NUM}_${SYSTEM_NAME}"
SYSTEM_FULL_PATH="$SYSTEMS_PATH/$SYSTEM_FOLDER"

echo -e "${GREEN}=== Unity System Structure Creator ===${NC}"
echo -e "시스템: ${YELLOW}$SYSTEM_NAME${NC}"
echo -e "경로: ${YELLOW}$SYSTEM_FULL_PATH${NC}"
echo ""

# 폴더 생성
mkdir -p "$SYSTEM_FULL_PATH/01_Interfaces"
mkdir -p "$SYSTEM_FULL_PATH/02_Core"
mkdir -p "$SYSTEM_FULL_PATH/03_Mono"

# 테스트 폴더 (01_Scripts 하위에 Tests가 있다고 가정)
TESTS_PATH="$SCRIPTS_PATH/05_Tests/$SYSTEM_NAME"
mkdir -p "$TESTS_PATH"

echo -e "${GREEN}폴더 생성 완료:${NC}"
echo "  $SYSTEM_FULL_PATH/01_Interfaces/"
echo "  $SYSTEM_FULL_PATH/02_Core/"
echo "  $SYSTEM_FULL_PATH/03_Mono/"
echo "  $TESTS_PATH/"
echo ""

# 빈 인터페이스 파일 생성
INTERFACE_FILE="$SYSTEM_FULL_PATH/01_Interfaces/I${SYSTEM_NAME}.cs"
cat > "$INTERFACE_FILE" << EOF
// I${SYSTEM_NAME}.cs
// Generated by create-structure.sh
// TODO: architect 에이전트가 내용 작성 예정

namespace Systems.${SYSTEM_NAME}
{
    public interface I${SYSTEM_NAME}
    {
        // 에이전트가 설계할 메서드들
    }
}
EOF

# 빈 컨트롤러 파일 생성
CONTROLLER_FILE="$SYSTEM_FULL_PATH/02_Core/${SYSTEM_NAME}Controller.cs"
cat > "$CONTROLLER_FILE" << EOF
// ${SYSTEM_NAME}Controller.cs
// Generated by create-structure.sh
// TODO: implementer 에이전트가 내용 작성 예정

namespace Systems.${SYSTEM_NAME}
{
    /// <summary>
    /// ${SYSTEM_NAME} 시스템의 핵심 로직 (Pure C# - TDD 대상)
    /// </summary>
    public class ${SYSTEM_NAME}Controller : I${SYSTEM_NAME}
    {
        // 에이전트가 구현할 로직
    }
}
EOF

# 빈 테스트 파일 생성
TEST_FILE="$TESTS_PATH/${SYSTEM_NAME}ControllerTests.cs"
cat > "$TEST_FILE" << EOF
// ${SYSTEM_NAME}ControllerTests.cs
// Generated by create-structure.sh
// TODO: implementer 에이전트가 테스트 작성 예정

using NUnit.Framework;
using Systems.${SYSTEM_NAME};

namespace Tests.${SYSTEM_NAME}
{
    [TestFixture]
    public class ${SYSTEM_NAME}ControllerTests
    {
        private ${SYSTEM_NAME}Controller _controller;

        [SetUp]
        public void SetUp()
        {
            _controller = new ${SYSTEM_NAME}Controller();
        }

        [Test]
        public void Placeholder_ShouldBeReplaced()
        {
            // TODO: 실제 테스트로 교체
            Assert.Pass("테스트 구현 필요");
        }
    }
}
EOF

echo -e "${GREEN}파일 생성 완료:${NC}"
echo "  $INTERFACE_FILE"
echo "  $CONTROLLER_FILE"
echo "  $TEST_FILE"
echo ""

# 생성 결과 요약 (에이전트가 파싱하기 쉬운 형태)
echo -e "${GREEN}=== 생성 완료 ===${NC}"
echo "SYSTEM_NAME=$SYSTEM_NAME"
echo "SYSTEM_PATH=$SYSTEM_FULL_PATH"
echo "INTERFACE_FILE=$INTERFACE_FILE"
echo "CONTROLLER_FILE=$CONTROLLER_FILE"
echo "TEST_FILE=$TEST_FILE"
echo "TESTS_PATH=$TESTS_PATH"
